# ============================================================================
# Crux-Webmail — Dovecot: main config
# ============================================================================

protocols = imap lmtp
listen    = *, ::

# Mail location — maildir bajo el volumen montado (dovecot_mail)
mail_location = maildir:/var/vmail/mailboxes/%d/%n

# Admin
admin_addresses = postmaster@crux.local

# SSL/TLS — STRICT (identidad propia: cert con SAN dovecot.crux.local)
ssl = required
ssl_cert     = </etc/crux-certs/dovecot.crt
ssl_key      = </etc/crux-certs/dovecot.key
ssl_ca       = </etc/crux-certs/ca-chain.crt

# Only TLS 1.2+
ssl_min_protocol_version = TLSv1.2
ssl_prefer_server_ciphers = no
ssl_cipher_suites = TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
ssl_cipher_list = ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305

# Auth mechanisms
auth_mechanisms = plain login

# Namespace
!include_try /etc/dovecot/conf.d/*.conf