# ============================================================================
# Crux-Webmail — Dovecot: main config
# ============================================================================

protocols = imap lmtp
listen    = *, ::

# Mail location — maildir bajo el volumen montado (dovecot_mail)
mail_location = maildir:/var/vmail/mailboxes/%d/%n

# Admin / postmaster (used by LDA/LMTP for bounces & DSNs)
postmaster_address = postmaster@crux.local

# SSL/TLS se configura en conf.d/10-ssl.conf (incluido más abajo)

# Auth mechanisms
auth_mechanisms = plain login

# Namespace
!include_try /etc/dovecot/conf.d/*.conf